"""Add date_of_import to CallInfo

Revision ID: 34cd9c5e9011
Revises: 7c65d3ca4efc
Create Date: 2024-06-27 16:42:55.722435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34cd9c5e9011'
down_revision = '7c65d3ca4efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_import', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('unique_call_info', type_='unique')
        batch_op.create_unique_constraint('unique_call_info', ['phone', 'phone1', 'phone2', 'phone3', 'phone4', 'Id_chain', 'Client_id', 'fio', 'all_summ', 'summ', 'summ_dolg', 'summ_perc', 'summ_mail', 'summ_perc_plus', 'day', 'product', 'Sud_vixod', 'Sud_resh', 'region', 'adress', 'anketa', 'status_of_call', 'Try', 'result1', 'result2', 'date_of_call', 'comment', 'phone_new', 'Operator', 'date_of', 'date_of_import'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_info', schema=None) as batch_op:
        batch_op.drop_constraint('unique_call_info', type_='unique')
        batch_op.create_unique_constraint('unique_call_info', ['phone', 'phone1', 'phone2', 'phone3', 'phone4', 'Id_chain', 'Client_id', 'fio', 'all_summ', 'summ', 'summ_dolg', 'summ_perc', 'summ_mail', 'summ_perc_plus', 'day', 'product', 'Sud_vixod', 'Sud_resh', 'region', 'adress', 'anketa', 'status_of_call', 'Try', 'result1', 'result2', 'date_of_call', 'comment', 'phone_new', 'Operator', 'date_of'])
        batch_op.drop_column('date_of_import')

    # ### end Alembic commands ###
