"""Add time_of_call column

Revision ID: e7516b7807ac
Revises: 4a1eec6e75af
Create Date: 2024-07-05 16:22:11.299132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7516b7807ac'
down_revision = '4a1eec6e75af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_of_call', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_info', schema=None) as batch_op:
        batch_op.drop_column('time_of_call')

    # ### end Alembic commands ###
